### ISSUE TITLE
Error during remote debugging initialization.

### ISSUE THREAD

**Issue by vladipus** [rocky/python2-trepan#10]
Getting the following error, during `trepan.api.debug(dbg_opts={'interface': intf}, post_mortem=False)`:

Traceback (most recent call last):
  File "/home/tellmebest/app/modules/api.py", line 165, in __init__
    post_mortem=False)
  File "/usr/local/lib/python2.7/dist-packages/trepan/api.py", line 186, in debug
    Mdebugger.debugger_obj = Mdebugger.Debugger(dbg_opts)
  File "/usr/local/lib/python2.7/dist-packages/trepan/debugger.py", line 320, in __init__
    self.core = Mcore.DebuggerCore(self, core_opts)
  File "/usr/local/lib/python2.7/dist-packages/trepan/lib/core.py", line 90, in __init__
    self.processor   = Mcmdproc.CommandProcessor(self, opts=proc_opts)
  File "/usr/local/lib/python2.7/dist-packages/trepan/processor/cmdproc.py", line 249, in __init__
    self.cmd_instances    = self._populate_commands()
  File "/usr/local/lib/python2.7/dist-packages/trepan/processor/cmdproc.py", line 857, in _populate_commands
    return self.populate_commands_easy_install(Mcommand)
  File "/usr/local/lib/python2.7/dist-packages/trepan/processor/cmdproc.py", line 927, in populate_commands_easy_install
    inspect.getmembers(command_mod, inspect.isclass)
UnboundLocalError: local variable 'command_mod' referenced before assignment

Also the documentation on how to start a remote debugging process seems to be missing on the new docs site...

**Comment by rocky** [comment]
Commit  [3d03089] might address the traceback. If not, give a more complete example of what you did so that I can replicate the problem. (I'm guessing you don't have ipython installed.)

As for info on remote debugging, I'll look at that when I get a chance.  Thanks for reporting it.

**Comment by rocky** [comment]
Haven't heard back. Assume this is addressed.
